[package]
name = "re_write_ce"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3.9", features = ["psapi", "minwindef", "processthreadsapi", "handleapi", "winnt", "memoryapi"] }